import { Router } from "express";

const router = Router();

const ASSETS = [
  {
    id: "ast-001",
    name: "Manhattan Commercial Tower Portfolio",
    category: "Real Estate",
    valuation: 2800000000,
    currency: "USD",
    aiRiskScore: 2.3,
    aiConfidence: 96.1,
    liquidityRating: "High",
    marketDemand: "Very High",
    status: "Tokenized",
    tokenSymbol: "MCTP",
    totalTokens: 2800000,
    availableTokens: 840000,
    location: "New York, USA",
    description: "Class-A commercial real estate portfolio comprising five Midtown Manhattan office towers with long-term institutional tenants.",
    historicalReturn: 8.4,
    yieldRate: 5.2,
  },
  {
    id: "ast-002",
    name: "Dubai Infrastructure Bond Series A",
    category: "Infrastructure",
    valuation: 1200000000,
    currency: "AED",
    aiRiskScore: 3.1,
    aiConfidence: 93.8,
    liquidityRating: "High",
    marketDemand: "High",
    status: "Tokenized",
    tokenSymbol: "DIBA",
    totalTokens: 1200000,
    availableTokens: 360000,
    location: "Dubai, UAE",
    description: "Sovereign-backed infrastructure bonds financing the expansion of Dubai International Airport Terminal 4 and related logistics infrastructure.",
    historicalReturn: 7.1,
    yieldRate: 6.3,
  },
  {
    id: "ast-003",
    name: "North Sea Energy Complex",
    category: "Energy",
    valuation: 4100000000,
    currency: "GBP",
    aiRiskScore: 4.2,
    aiConfidence: 91.4,
    liquidityRating: "Medium",
    marketDemand: "High",
    status: "Tokenized",
    tokenSymbol: "NSEC",
    totalTokens: 4100000,
    availableTokens: 1230000,
    location: "Aberdeen, Scotland",
    description: "Integrated North Sea oil & gas extraction and processing complex with 25-year remaining operational life and proven reserves of 340M barrels.",
    historicalReturn: 11.2,
    yieldRate: 8.7,
  },
  {
    id: "ast-004",
    name: "Singapore Carbon Credit Portfolio",
    category: "Carbon Credits",
    valuation: 340000000,
    currency: "SGD",
    aiRiskScore: 1.8,
    aiConfidence: 97.3,
    liquidityRating: "Very High",
    marketDemand: "Very High",
    status: "Tokenized",
    tokenSymbol: "SCCP",
    totalTokens: 340000,
    availableTokens: 170000,
    location: "Singapore",
    description: "Verified carbon credit portfolio from 18 certified reforestation projects across Southeast Asia. Gold Standard and VCS certified.",
    historicalReturn: 22.8,
    yieldRate: 0,
  },
  {
    id: "ast-005",
    name: "Global Commodity Index Fund",
    category: "Commodities",
    valuation: 890000000,
    currency: "USD",
    aiRiskScore: 3.5,
    aiConfidence: 89.6,
    liquidityRating: "High",
    marketDemand: "High",
    status: "Tokenized",
    tokenSymbol: "GCIF",
    totalTokens: 890000,
    availableTokens: 267000,
    location: "Chicago, USA",
    description: "Diversified commodity index fund tracking gold, silver, crude oil, natural gas, and agricultural commodities with institutional custody.",
    historicalReturn: 9.3,
    yieldRate: 4.1,
  },
  {
    id: "ast-006",
    name: "European Private Credit Fund III",
    category: "Private Credit",
    valuation: 2100000000,
    currency: "EUR",
    aiRiskScore: 2.9,
    aiConfidence: 94.7,
    liquidityRating: "Medium",
    marketDemand: "High",
    status: "Tokenized",
    tokenSymbol: "EPCF",
    totalTokens: 2100000,
    availableTokens: 630000,
    location: "Frankfurt, Germany",
    description: "Direct lending fund providing senior secured financing to European mid-market companies. Diversified across 47 portfolio companies.",
    historicalReturn: 12.4,
    yieldRate: 9.8,
  },
  {
    id: "ast-007",
    name: "Tokyo Mixed-Use Development",
    category: "Real Estate",
    valuation: 1800000000,
    currency: "JPY",
    aiRiskScore: 2.6,
    aiConfidence: 95.2,
    liquidityRating: "High",
    marketDemand: "Very High",
    status: "Tokenized",
    tokenSymbol: "TMUD",
    totalTokens: 1800000,
    availableTokens: 720000,
    location: "Tokyo, Japan",
    description: "Premier mixed-use development in Shibuya comprising luxury residential towers, Grade-A office space, and retail podium.",
    historicalReturn: 7.8,
    yieldRate: 4.9,
  },
  {
    id: "ast-008",
    name: "Australian LNG Terminal",
    category: "Energy",
    valuation: 3200000000,
    currency: "AUD",
    aiRiskScore: 3.8,
    aiConfidence: 92.1,
    liquidityRating: "Medium",
    marketDemand: "High",
    status: "Tokenized",
    tokenSymbol: "ALNG",
    totalTokens: 3200000,
    availableTokens: 960000,
    location: "Darwin, Australia",
    description: "Operational LNG export terminal with 20-year offtake agreements with Japanese and Korean utility companies.",
    historicalReturn: 10.6,
    yieldRate: 7.4,
  },
  {
    id: "ast-009",
    name: "Brazilian Agri-Bond Portfolio",
    category: "Commodities",
    valuation: 560000000,
    currency: "USD",
    aiRiskScore: 4.6,
    aiConfidence: 88.3,
    liquidityRating: "Medium",
    marketDemand: "Medium",
    status: "Tokenizing",
    tokenSymbol: "BABP",
    totalTokens: 560000,
    availableTokens: 560000,
    location: "São Paulo, Brazil",
    description: "Agricultural bonds backed by certified soybean and sugarcane production assets in Mato Grosso state.",
    historicalReturn: 14.2,
    yieldRate: 11.3,
  },
  {
    id: "ast-010",
    name: "Swiss Private Equity Fund",
    category: "Private Credit",
    valuation: 1400000000,
    currency: "CHF",
    aiRiskScore: 2.4,
    aiConfidence: 96.8,
    liquidityRating: "Low",
    marketDemand: "High",
    status: "Tokenized",
    tokenSymbol: "SPEF",
    totalTokens: 1400000,
    availableTokens: 280000,
    location: "Geneva, Switzerland",
    description: "Buyout fund targeting European industrial and technology companies. Vintage 2022 with strong performance tracking.",
    historicalReturn: 16.9,
    yieldRate: 0,
  },
  {
    id: "ast-011",
    name: "Riyadh Vision 2030 REIT",
    category: "Real Estate",
    valuation: 5200000000,
    currency: "SAR",
    aiRiskScore: 2.1,
    aiConfidence: 97.8,
    liquidityRating: "Very High",
    marketDemand: "Very High",
    status: "Tokenized",
    tokenSymbol: "RV30",
    totalTokens: 5200000,
    availableTokens: 1560000,
    location: "Riyadh, Saudi Arabia",
    description: "REIT aligned with Saudi Vision 2030 comprising NEOM-adjacent hospitality, logistics, and smart city infrastructure assets.",
    historicalReturn: 18.3,
    yieldRate: 6.8,
  },
  {
    id: "ast-012",
    name: "Southeast Asia Renewable Energy Portfolio",
    category: "Energy",
    valuation: 1650000000,
    currency: "USD",
    aiRiskScore: 2.7,
    aiConfidence: 94.1,
    liquidityRating: "High",
    marketDemand: "Very High",
    status: "Tokenizing",
    tokenSymbol: "SARE",
    totalTokens: 1650000,
    availableTokens: 1650000,
    location: "Singapore",
    description: "Diversified renewable energy portfolio across solar farms in Vietnam, wind installations in Philippines, and hydro assets in Indonesia.",
    historicalReturn: 13.7,
    yieldRate: 8.2,
  },
];

router.get("/assets", (req, res) => {
  let result = [...ASSETS];
  const { category, status } = req.query;
  if (category && category !== "All") {
    result = result.filter((a) => a.category === category);
  }
  if (status) {
    result = result.filter((a) => a.status === status);
  }
  res.json(result);
});

router.get("/assets/:id", (req, res) => {
  const asset = ASSETS.find((a) => a.id === req.params.id);
  if (!asset) {
    res.status(404).json({ error: "Asset not found" });
    return;
  }
  res.json(asset);
});

router.post("/assets", (req, res) => {
  const { name, category, valuation, currency, location, description } = req.body;
  const newAsset = {
    id: `ast-${Date.now()}`,
    name,
    category,
    valuation,
    currency: currency || "USD",
    aiRiskScore: Math.round((Math.random() * 5 + 1) * 10) / 10,
    aiConfidence: Math.round((85 + Math.random() * 12) * 10) / 10,
    liquidityRating: "Medium",
    marketDemand: "Medium",
    status: "Tokenizing",
    tokenSymbol: name.split(" ").map((w: string) => w[0]).join("").toUpperCase().slice(0, 5),
    totalTokens: Math.floor(valuation / 1000),
    availableTokens: Math.floor(valuation / 1000),
    location: location || "",
    description: description || "",
    historicalReturn: Math.round((Math.random() * 15 + 5) * 10) / 10,
    yieldRate: Math.round((Math.random() * 8 + 2) * 10) / 10,
  };
  res.status(201).json(newAsset);
});

export default router;
